### ISSUE TITLE
Broken documentation link in image

### ISSUE THREAD

**Issue by bw908** [commontorizon/Documentation#4]
On login the images reference `https://github.com/commontorizon/Documentation/blob/main/PRE-BUILT-DEV.md` for more information, but this document doesn't actually exist.

**Comment by microhobby** [comment]
oops, yeah this needs to be uploaded, thanks to point

**Comment by bw908** [comment]
Thanks. Are there plans to also provide pre-built release images (minus the dev tools) that are suitable for production, or is this expected to be done by the end-user?
